- name: Install "redis" node.js package.
  npm:
    name: redis
    path: "{{playbook_dir}}/etc/bin"

- name: Ensure Redis is present
  apt: pkg=redis-server state=latest
  become: yes

- name: Ensure Redis Configuration
  template: 
    src: "{{playbook_dir}}/roles/redis/files/redis.conf"
    dest: "{{playbook_dir}}/etc/bin/redis.conf owner=root group=root mode=0777"
  become: yes