- name: uploading bootstrap file.zip to remote host servers
  copy:
    src: /etc/ansible/T-DOP-600_bootstrap_ansible_applications.tar
    dest: /etc/ansible/BootStrap.tar
    owner: root
    group: root
    mode: 0777

- name: Unarchive a file that is already on the remote machine
  unarchive:
    src: /etc/ansible/BootStrap.tar
    dest: /etc/ansible/BootStrap/
    remote_src: yes

- name: Install "express" node.js 
  npm:
    name: express
    path: /etc/ansible/BootStrap/T-DOP-600_bootstrap_ansible_applications/

# - name: Install "redis" node.js package.
#   npm:
#     name: redis
#     path: /etc/ansible/BootStrap/T-DOP-600_bootstrap_ansible_applications/

# - name: Ensure express is present
#   apt: pkg=express state=latest
#   sudo: true

# - name: Ensure express is started
#   service: name=express state=started enabled=yes
#   sudo: true

#  - name: enable redis service
#   service: name=redis enabled=yes

#  - name: Make sure express service is running
#    systemd:
#     state: started
#     name: express
    
# - name: Make sure redis service is running
#   systemd:
#     state: started
#     name: redis

- name: Template a j2 file to server
  template:
    src: /etc/ansible/roles/deploy/templates/boot.j2
    dest: /etc/ansible/BootStrap/T-DOP-600_bootstrap_ansible_applications/
    owner: root
    group: root
    mode: '0777'

- name: start systemd.service
  systemd: 
    state: started 
    name: my-awesome-app
    daemon_reload: yes