#if it is done by this order, we should do the base, redis and postgresql first.

- hosts: all
  roles:
    - base

- hosts: web
  roles: 
    - poll

- hosts: redis
  roles:
    - redis
  vars:
    redis_port: 4242
    redis_databases: 1

- hosts: worker
  roles:
    - worker

- hosts: postgresql
  roles:
    - postgresql

- hosts: web
  roles: 
    - result