#if it is done by this order, we should do the base, redis and postgresql first.

- hosts: all
  roles:
    - result
    - base

- hosts: postgresql
  roles:
    - postgresql


- hosts: web
  roles: 
    - deploy

- hosts: redis
  roles:
    - redis
  vars:
    redis_port: 4242
    redis_databases: 1