
- name: install python
  apt: name=python-software-properties state=present update_cache=yes cache_valid_time=43200

- name: install packages
  apt: name={{item}} state=installed
  with_items:
    - python3-pip
    - python3-dev

- name: Upgrade pip
  pip: name=pip state=latest
  tags:
    - packages

- name: copy the file of the host
  copy:
    src: {{playbook_dir}}/poll.tar
    dest: /etc/bin

- name: unarhive the file
  unarchive:
    src: /etc/bin/poll.tar
    dest: /etc/bin
    remote_src: yes

- name: install the dependency
  pip:
    requirements: /etc/bin/poll/requirements.txt

- name: and run it
  shell: python3 app.py
    chdir: /etc/bin/poll


- name: Make sure a service is running
  systemd:
    state: started
    name: poll.service

- name: send data to redis
#there is a return and we have to send it to another server